### ISSUE TITLE
Can't play an audio(Intermittent)

### ISSUE THREAD

**Issue by gerry05** [idofilus/flutter_audio#18]
W/MediaPlayer(24751): mediaplayer went away with unhandled events
I/System.out(24751): onMethodCall method=player.pause uid=7d66090b-6028-47ce-a315-c9a873ac6076
E/MethodChannel#audio(24751): Failed to handle method call
E/MethodChannel#audio(24751): java.lang.IllegalStateException
E/MethodChannel#audio(24751):   at android.media.MediaPlayer.isPlaying(Native Method)
E/MethodChannel#audio(24751):   at com.idofilus.audio.AudioPlayer.pause(AudioPlayer.java:201)
E/MethodChannel#audio(24751):   at com.idofilus.audio.AudioPlugin.onMethodCall(AudioPlugin.java:58)
E/MethodChannel#audio(24751):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#audio(24751):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#audio(24751):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#audio(24751):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#audio(24751):   at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#audio(24751):   at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#audio(24751):   at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#audio(24751):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#audio(24751):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#audio(24751):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/System.out(24751): onMethodCall method=player.pause uid=9f114197-cdfe-443f-a4ae-905f871017fc
V/com.idofilus.audio.AudioPlayer(24751): [invoke] player.onPause 9f114197-cdfe-443f-a4ae-905f871017fc => null
I/System.out(24751): onMethodCall method=player.play uid=9f114197-cdfe-443f-a4ae-905f871017fc
V/com.idofilus.audio.AudioPlayer(24751): playing:
V/com.idofilus.audio.AudioPlayer(24751): [invoke] player.onBuffering 9f114197-cdfe-443f-a4ae-905f871017fc => 0
V/MediaPlayer(24751): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(24751): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/com.idofilus.audio.AudioPlayer(24751): Failed to play audio, invalid data source: setDataSource failed.
E/flutter (24751): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, null, null)
E/flutter (24751): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (24751): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (24751): <asynchronous suspension>
E/flutter (24751): #2      AudioPlayer.invoke (package:audio/audio.dart:138:20)
E/flutter (24751): <asynchronous suspension>
E/flutter (24751): #3      AudioPlayer.pause (package:audio/audio.dart:119:11)
E/flutter (24751): <asynchronous suspension>
E/flutter (24751): #4      Audio.play.<anonymous closure> (package:audio/audio.dart:331:22)
E/flutter (24751): <asynchronous suspension>
E/flutter (24751): #5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
E/flutter (24751): #6      Audio.play (package:audio/audio.dart:330:15)
E/flutter (24751): <asynchronous suspension>
E/flutter (24751): #7      GroupMessageState.onPlay (package:rocket_mentor/screens/grouplist/index.dart:683:19) E/flutter (24751): #8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
E/flutter (24751): #9      GroupMessageState.onPlay (package:rocket_mentor/screens/grouplist/index.dart:666:7)
E/flutter (24751): #10     GroupMessageState.audioInit.<anonymous closure> (package:rocket_mentor/screens/grouplist/index.dart:604:14)
E/flutter (24751): #11     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (24751): #12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (24751): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (24751): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (24751): #15     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (24751): #16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (24751): #17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (24751): #18     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (24751): #19     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24751): #20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (24751): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (24751): #22     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (24751): #23     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (24751): #24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (24751): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (24751): #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (24751): #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by idofilus** [comment]
I already started to deeply checking the library, improve, add features and add testing.
This means I'll be able to go over all the issues whether is a bug report of an improvement.
Hopefully moving this library to a stable version and support web as well.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA
